version: "3.8"

services:
  database:
    image: mysql:latest
    container_name: mysql-camion-saveur
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-camion-saveur
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin-camion-saveur:
    image: phpmyadmin:latest
    container_name: phpmyadmin-camion-saveur
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"

  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  dbdata:
